# Mission: B4.6 Example Repository
# Sprint: Sprint 4 - Phase 4/5 Release & Ecosystem

missionId: "B4.6_example-repository"
version: "1.0.0"

objective: |
  Create practical, runnable examples in-repo demonstrating all 5 protocols with realistic use cases.
  Provide simple Node.js scripts that developers can run immediately to see protocols in action.
  No external repo, Docker, or complex infrastructure - just clean, educational code.

context: |
  SIMPLIFIED SCOPE - No external repo, no Docker/Kafka complexity.
  
  Create examples/ directory in main repo with runnable Node.js scripts.
  Each example demonstrates a specific protocol or pattern with:
  - Realistic manifests
  - Working code that runs immediately
  - Clear comments explaining what's happening
  - Self-contained (no external services)
  
  Target: Developer clones repo, runs `node examples/data-validation.js`, sees protocol in action.
  
  Already have: test manifests, integration tests, docs examples
  Need: Simple runnable scripts showing practical usage patterns

successCriteria:
  - "examples/ directory created in repo"
  - "6+ runnable scripts demonstrating all 5 protocols"
  - "Each script runs successfully: node examples/[name].js"
  - "Realistic manifests showing practical patterns"
  - "Clear inline comments explaining what's happening"
  - "examples/README.md with quick start"
  - "No external dependencies beyond @cpms packages"
  - "Each example self-contained and educational"
  - "Can run examples in <1 minute from clone"

deliverables:
  - "examples/ directory with 6+ runnable scripts"
  - "examples/README.md with quick start guide"
  - "Realistic manifests for each protocol type"
  - "Clear comments and educational value in code"
  - "No external service dependencies"

domainFields:
  type: "Build.Implementation.v1"
  
  researchFoundation:
    - finding: "Full-stack integration patterns from foundational docs"
      sourceMission: "foundational-docs/Cross-Protocol Manifest System-k2.md"
    - finding: "Published packages available on npm"
      sourceMission: "B4.3_npm-publishing-setup"
    - finding: "GitHub Action available for CI/CD"
      sourceMission: "B4.5_github-action-package"
      
  implementationScope:
    coreDeliverable: "In-repo examples/ directory with 6+ practical, runnable scripts"
    outOfScope:
      - "External proto-examples repository"
      - "Docker/Kafka/Express infrastructure"
      - "Complex multi-service setup"
      - "CI/CD workflow examples (already in repo)"
      - "Production-ready application code"

  orchestrationPatterns:
    selectedPattern: "none"
    mutuallyExclusive: true
    configuration:
      none:
        enabled: true
        notes: "Example creation is straightforward, single agent optimal"

  runtimeTopology:
    stateDirectories:
      - "telemetry/events"
    telemetry:
      streamFormat: "jsonl"
      retention: "mission"
      requiredEvents:
        - "repo_init"
        - "app_implementation"
        - "manifests_created"
        - "integration_verified"

  validationProtocol:
    - validator: "Claude"
      focus: "Code quality and educational value"
    - validator: "Gemini"
      focus: "Best practices and completeness"

  llmAsJudgeValidation:
    enabled: true
    validationCriteria:
      - "Examples are realistic and useful"
      - "Comments explain why, not just what"
      - "Setup instructions are clear and work"
      - "All dependencies specified correctly"
      - "No hardcoded secrets or credentials"

  failureEscalation:
    tier_1_automatic_retry:
      conditions:
        - "docker_build_failure"
        - "npm_install_timeout"
      behavior: "Retry setup steps"
    tier_4_human_escalation:
      enforcement: "If example unclear, get feedback before marking complete"

  qualityGates:
    preCommit:
      - "All examples run successfully"
      - "Docker Compose up works cleanly"
      - "CI pipeline passes"
      - "README instructions verified"
      
    postImplementation:
      - "Fresh clone and setup works in <5 minutes"
      - "All manifests validate successfully"
      - "Integration tests pass"
      - "No broken links or missing files"

  handoffContext:
    completed:
      - "Example repository published"
      - "All protocols demonstrated"
      - "Integration patterns documented"
    interfaces:
      - "Repository: proto-examples (GitHub)"
      - "Quick start: README.md"
      - "Manifests: /manifests/"
    assumptions:
      - "Users have Docker installed"
      - "Users have Node.js 20+ installed"
      - "Users have basic CLI familiarity"
    nextMission: "B4.7_community-setup"
    blockers:
      - "Blocked by B4.3_npm-publishing-setup (needs published packages)"
      - "Blocked by B4.5_github-action-package (for CI example)"
    researchRequired: false

---

# Implementation Plan

## Phase 1: Setup examples/ Directory (15 minutes)

### 1.1 Create Structure
```bash
mkdir -p examples/manifests
```

### 1.2 Examples to Create
1. `examples/01-data-validation.js` - Load manifest, validate, show PII detection
2. `examples/02-breaking-changes.js` - Diff two manifests, detect breaking changes
3. `examples/03-api-sdk-preview.js` - Show SDK generation from API manifest
4. `examples/04-agent-capabilities.js` - URN linking, capability matching
5. `examples/05-catalog-analysis.js` - Load multiple manifests, detect cycles
6. `examples/06-full-workflow.js` - End-to-end validation → diff → generate
7. `examples/README.md` - Quick start guide

## Phase 2: Create Example Scripts (60 minutes)

### 2.1 Example 01: Data Validation
`examples/01-data-validation.js` - Demonstrates Data Protocol basics

### 2.2 Data Protocol Example
`manifests/data/users.json`:
```json
{
  "dataset": {
    "name": "users",
    "owner": "user-service",
    "lifecycle": { "status": "active" }
  },
  "schema": {
    "primary_key": "user_id",
    "fields": {
      "user_id": { "type": "uuid", "required": true },
      "email": { "type": "string", "pii": true, "required": true },
      "name": { "type": "string", "pii": true },
      "created_at": { "type": "timestamp", "required": true }
    }
  },
  "governance": {
    "policy": {
      "classification": "pii",
      "retention": "7 years"
    }
  }
}
```

### 2.3 Event Protocol Example
`manifests/events/order-created.json`:
```json
{
  "event": {
    "name": "order.created",
    "version": "1.0.0",
    "description": "Emitted when new order is created"
  },
  "schema": {
    "fields": {
      "order_id": { "type": "string", "required": true },
      "user_id": { "type": "string", "required": true },
      "total": { "type": "number", "required": true },
      "items": { "type": "array", "required": true }
    }
  },
  "transport": {
    "platform": "kafka",
    "topic": "orders.created",
    "partitionKey": "user_id"
  }
}
```

### 2.4 API Protocol Example
`manifests/api/checkout-api.json`:
```json
{
  "api": {
    "name": "checkout-api",
    "version": "1.0.0",
    "baseUrl": "https://api.example.com/v1"
  },
  "endpoints": [
    {
      "path": "/checkout",
      "method": "POST",
      "operationId": "createOrder",
      "request": {
        "contentType": "application/json",
        "schema": "urn:proto:data:order@v1"
      },
      "responses": {
        "201": {
          "description": "Order created",
          "schema": { "type": "object" }
        }
      }
    }
  ]
}
```

### 2.5 Agent Protocol Example
`manifests/agents/fraud-detection.json`:
```json
{
  "agent": {
    "name": "fraud-detection-agent",
    "version": "1.0.0",
    "description": "Analyzes orders for fraud patterns"
  },
  "capabilities": {
    "tools": [
      {
        "name": "analyzeOrder",
        "description": "Analyze order for fraud indicators",
        "inputSchema": "urn:proto:data:order@v1"
      }
    ]
  },
  "relationships": {
    "consumes": ["urn:proto:event:order.created@v1"],
    "produces": ["urn:proto:event:fraud.detected@v1"]
  }
}
```

### 2.6 Application Code
Simple Express app demonstrating protocol usage:
```javascript
// src/api/server.js
import express from 'express';
import { createAPIProtocol } from '@cpms/api';
import manifest from '../../manifests/api/checkout-api.json' assert { type: 'json' };

const api = createAPIProtocol(manifest);
const app = express();

app.post('/checkout', (req, res) => {
  // Validate request against manifest
  const validation = api.validate();
  if (!validation.ok) {
    return res.status(400).json(validation.results);
  }
  
  // Process order...
  res.status(201).json({ orderId: '...' });
});

app.listen(3000);
```

## Phase 3: Docker Setup (30 minutes)

### 3.1 Dockerfile
```dockerfile
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

EXPOSE 3000

CMD ["node", "src/api/server.js"]
```

### 3.2 Docker Compose
```yaml
version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./manifests:/app/manifests
  
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
```

## Phase 4: CI/CD Integration (20 minutes)

### 4.1 GitHub Actions Workflow
`.github/workflows/validate.yml`:
```yaml
name: Validate Manifests

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: proto/validate-action@v1
        with:
          manifest-glob: 'manifests/**/*.json'
          fail-on-breaking: true
          comment-on-pr: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm test
```

## Phase 5: Documentation (45 minutes)

### 5.1 Comprehensive README
```markdown
# Cross-Protocol Manifest System Examples

Real-world examples demonstrating protocol integration.

## Quick Start

\`\`\`bash
# Clone repository
git clone https://github.com/[org]/proto-examples.git
cd proto-examples

# Install dependencies
npm install

# Start services
docker-compose up

# Validate manifests
npm run validate

# Run integration tests
npm test
\`\`\`

## Examples

### Data Protocol
[Explain user database manifest]

### Event Protocol
[Explain order event manifest]

### API Protocol
[Explain checkout API manifest]

### Agent Protocol
[Explain fraud detection agent manifest]

## Integration Patterns

[Document common patterns]

## Best Practices

[Document best practices]
```

### 5.2 Pattern Documentation
Create `docs/patterns.md` explaining:
- URN linking patterns
- Catalog analysis workflows
- Migration strategies
- Testing approaches

## Phase 6: Testing (30 minutes)

### 6.1 Integration Tests
```javascript
// tests/integration.test.js
import { describe, test } from 'node:test';
import assert from 'node:assert';
import { createDataProtocol } from '@cpms/data';
import { createEventProtocol } from '@cpms/event';
import { createAPICatalog } from '@cpms/api';

describe('Integration Tests', () => {
  test('manifests validate successfully', async () => {
    // Load all manifests
    // Validate each
    // Assert all pass
  });
  
  test('URN references resolve', async () => {
    // Test cross-protocol URN resolution
  });
  
  test('catalog analysis works', async () => {
    // Test catalog functionality
  });
});
```

### 6.2 Manual Testing
```bash
# Clean install test
rm -rf node_modules
npm install

# Validate manifests
npm run validate

# Start services
docker-compose up

# Run tests
npm test
```

## Checklist

- [ ] Repository created
- [ ] Example application implemented
- [ ] 10+ manifests created (covering all protocols)
- [ ] Docker setup working
- [ ] CI/CD pipeline operational
- [ ] README comprehensive
- [ ] Integration tests passing
- [ ] Best practices documented
- [ ] Fresh clone works in <5 minutes
- [ ] All protocols demonstrated
- [ ] Comments explain patterns clearly

